name: "build"
on:
  pull_request:
  push:
jobs:
  mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    - uses: cachix/cachix-action@v15
    - run: nix build
